---
# Container descriptor
- descriptor: "pip-services:context-info:default:default:1.0"
  name: "payments"
  description: "Payments microservice from Pip.Services library"

# Console logger
- descriptor: "pip-services:logger:console:default:1.0"
  level: "trace"

# Perfomance counter that post values to log
- descriptor: "pip-services:counters:log:default:1.0"

# Controller
- descriptor: "pip-services-payments:controller:default:default:1.0"

# PayPal payment system
- descriptor: "pip-services-payments:connector:paypal:default:1.0"
  options:
    sandbox: true
  credential:
    access_id: "{{PAYPAL_ACCESS_ID}}"
    access_key: "{{PAYPAL_ACCESS_KEY}}"

# Stripe payment system
- descriptor: "pip-services-payments:connector:stripe:default:1.0"
  options:
    timeout: 80000
  credential:
    access_key: "{{STRIPE_ACCESS_KEY}}" 

# Common HTTP endpoint
- descriptor: "pip-services:endpoint:http:default:1.0"
  connection:
    protocol: http
    host: 0.0.0.0
    port: {{HTTP_PORT}}{{#unless HTTP_PORT}}8080{{/unless}}

# HTTP endpoint service version 1.0
- descriptor: "pip-services-payments:service:http:default:1.0"

# Hearbeat service
- descriptor: "pip-services:heartbeat-service:http:default:1.0"

# Status service
- descriptor: "pip-services:status-service:http:default:1.0"
